name: Create meeting note

on:
  schedule:
    - cron: '0 5 * * 3' # Every Wednesday afternoon

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
    - uses: actions/checkout@v2
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MEETING_SEQUENTIAL_ID: ${{steps.buildnumber.outputs.build_number}}
